#' rsd raw vs normalized.
#' @param obj_old A massdataset. raw data
#' @param obj_new A massdataset. normalized data
#' @param x_loc Integer Position of lables on the x-axis.
#' @param x_loc Integer Position of lables on the y-axis.
#' @param QC_tag character, QC tags in sample_info.
#' @param interactive logic; if true, generated a interactive 3D pca plot, if not, generated a 2d pca plot.
#' @param showImg logic; if true, print image on screen, if false, do not print.
#' @importFrom magrittr %>%
#' @importFrom dplyr select group_by summarise mutate case_when inner_join filter
#' @importFrom tibble rownames_to_column
#' @importFrom PCAtools pca
#' @importFrom crayon green bold italic red yellow
#' @importFrom plotly plot_ly
#' @importFrom massdataset activate_mass_dataset extract_expression_data
#' @importFrom ggplot2 geom_point scale_color_manual geom_vline geom_hline geom_abline geom_label xlim ylim labs theme_bw theme element_line element_rect element_text
#' @importFrom tidyr pivot_longer
#' @return rsd_plt a 3D pca
#' @export

IMO_plt_rsd = function(obj_old,obj_new,QC_tag,x_loc = c(120,110),y_loc = c(15,110),interactive = F,showImage=T){
  msg_yes = green$bold$italic
  msg_no = red$bold$italic
  msg_warning = yellow$bold$italic
  if (class(obj_old) != 'mass_dataset' | class(obj_new) != 'mass_dataset') {
    message(msg_no("error: Only obj which generated by massdataset accepted! Please check your input." ))
    return()
  }
  # calculate rsd for old object and new object.
  rsd_before <-
    obj_old %>%
    activate_mass_dataset("sample_info") %>%
    dplyr::filter(class == QC_tag) %>%
    extract_expression_data() %>%
    rownames_to_column("ID") %>%
    pivot_longer(contains(QC_tag),names_to = "tag",values_to = "value") %>%
    select(-tag) %>%
    group_by(ID) %>%
    summarise(
      raw.rsd = (sd(value,na.rm = T)/mean(value,na.rm = T))*100
    )
  rsd_after <-
    obj_new %>%
    activate_mass_dataset("sample_info") %>%
    dplyr::filter(class == QC_tag) %>%
    extract_expression_data() %>%
    rownames_to_column("ID") %>%
    pivot_longer(contains(QC_tag),names_to = "tag",values_to = "value") %>%
    select(-tag) %>%
    group_by(ID) %>%
    summarise(
      norm.rsd = (sd(value,na.rm = T)/mean(value,na.rm = T))*100
    )
  join_rsd <- inner_join(rsd_before,rsd_after,by = "ID") %>%
    mutate(
      norm_tag = case_when(
        norm.rsd <= 30 ~ "RSD ≤ 30",
        TRUE ~ "RSD > 30 "
      ),
      raw_tag = case_when(
        raw.rsd <= 30 ~ "RSD ≤ 30",
        TRUE ~ "RSD > 30 "
      )
    )
  #
  n1 = join_rsd %>% group_by(norm_tag) %>% summarise(num = n())

  rsd_plt = ggplot(data = join_rsd,mapping = aes(x = raw.rsd,y = norm.rsd,color = norm_tag)) +
    geom_point(size = 1.2,alpha =.8)+
    scale_color_manual(values = c("RSD ≤ 30" = "salmon","RSD > 30" = "grey30"))+
    geom_vline(xintercept = 30,linetype = "dashed",color = "red")+
    geom_hline(yintercept = 30,linetype = "dashed",color = "red")+
    geom_abline(slope = 1,linetype = "dashed",color = "red")+
    geom_label(
      data = data.frame(
        x = x_loc,
        y = y_loc,
        label = paste0("n=",c(n1[2,2],n1[1,2])),
        color = (c("RSD ≤ 30","RSD > 30"))
      ),
      mapping = aes(x = x,y = y,label = label,color= color),alpha = .8
    )+
    xlim(0,150)+
    ylim(0,150)+
    labs(x = "RSD of raw peak area",y = "RSD of svr normalized peak area")+
    theme_bw()+
    theme(
      line = element_line(size = 2,color = "black"),
      rect = element_rect(size = 2, color = "black"),
      axis.text = element_text(size = 14, color = "black"),
      axis.title = element_text(size = 16,color = "black",face = "bold")
    )
  if (isTRUE(showImage)) {
    print(rsd_plt)
  }
  out = list(
    rsd_tbl = join_rsd,
    plot = rsd_plt
  )
  return(out)
}
